"""title_phrases_and_phrase_offsets

Revision ID: 06492e8febcd
Revises: b33f248bf1d6
Create Date: 2026-04-17 14:59:39.316017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06492e8febcd'
down_revision: Union[str, Sequence[str], None] = 'b33f248bf1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
